### PR TITLE
Remove 'raw' field from 'testpilot' schema

### PR DESCRIPTION
**Pull request by 6a68**
Refs #58 and mozilla/testpilot#2313.

### CODE REVIEW

**Comment by 6a68** [comment]
@ncloudioj How do you want to handle orchestrating this schema change? Test Pilot currently does not use the ping-centre client, but just fires a ping directly to the endpoint. Will Ping Centre accept both the old and new versions of the schema? Should we add a version number to the schema at this point?

**Comment by ncloudioj** [comment]
The clients just simply switch to the new schema, we'll update the related ETL jobs to support both the old and new schemas. Note that the "raw" field will remain in the Redshift database, since Redshift doesn't support "ALTER TABLE DROP COLUMN". As a result, we'll populate this field with zero value, i.e. "n/a".

@6a68 Any other concerns?

**Comment by ncloudioj** [comment]
Oops, looks like there is a tiny coverage drop though. @6a68 Could you take a quick look about it please?

**Comment by ncloudioj** [comment]
@6a68 FYI, the ETL update for this schema change has landed in prod. The clients can send the pings in new schema now.

**Comment by 6a68** [comment]
> FYI, the ETL update for this schema change has landed in prod.

@ncloudioj fantastic! looking at the coverage drop

**Comment by 6a68** [comment]
@ncloudioj I'm confused by the coveralls coverage drop. It seems to affect [a line](https://coveralls.io/builds/10568074/source?filename=src%2Fping-centre.js#L19) that wasn't affected by the change (which was just to remove the 'raw' field tests). Any idea what I might be missing?

**Comment by ncloudioj** [comment]
@6a68 Go ahead merge it :shipit: . I think Coveralls just miscalculated it.

**Pull request merged**
