### PR TITLE
Add Test Pilot schema

### PR DESCRIPTION
**Pull request by 6a68**
Hey @emtwo, I've taken a first pass at a testpilot schema. Comments welcome :-)

I've uploaded a sample `testpilot` ping here: https://gist.github.com/6a68/4fdc2a1d848bb86f089bf8cf4472a89f

Should I add a sample ping and some unit tests to this PR?

### CODE REVIEW

**Comment by 6a68** [comment]
@ncloudioj Mind taking another look? Added some tests.

**Comment by ncloudioj** [comment]
All set! R+ @6a68

**Comment by 6a68** [comment]
hope I'm not being too cavalier by merging it myself (/me has github powers)

**Comment by ncloudioj** [comment]
@6a68 Haha, yup, that's the way to go. You merge your own PR once it gets r+.

**Pull request merged**
